### PR TITLE
toggle button added

### LINKED ISSUE #22: Add dark mode to the website
I would like to add toggle button for dark mode to your website.
I am opening this issue under hacktoberfest.
Can you assign it to me?

### PR DESCRIPTION
**Pull request by Laxmankohar**
Issue closes #22 
I have added toggle button by which we can change from dark to light and vice versa.

### CODE REVIEW

**Comment by abhishek23012000** [comment]
> Issue closes #22 I have added toggle button by which we can change from dark to light and vice versa.

U can also change logo of website and make pull request

**Comment by Laxmankohar** [comment]
> > Issue closes #22 I have added toggle button by which we can change from dark to light and vice versa.
> 
> U can also change logo of website and make pull request

What kind of logo do you want?

**Comment by abhishek23012000** [comment]
any logo which are fit for this website

**Comment by Laxmankohar** [comment]
wait i will be sending sample . After that you decide, ok?

**Pull request merged**
